import assert from 'node:assert/strict'
import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { parseEnv as parseNodeEnv } from 'node:util'
import { createVaultThroughUI } from './onboarding.mjs'

const { _electron } = await import(pathToFileURL(process.env.JIAZI_PLAYWRIGHT_MODULE).href)
const root = process.cwd(), output = resolve(root, 'output/playwright')
const data = resolve(output, `env-data-${Date.now()}`)
await mkdir(data, { recursive: true })
const report = [], errors = [], password = 'env-smoke-master-password'
let application, page, originalClipboard
const installed = process.env.JIAZI_INSTALLED_EXE
const pass = (name) => { report.push(name); console.log('PASS ' + name) }
const call = (command, args) => page.evaluate(({ command, args }) => window.jiaziVault.invoke(command, args), { command, args })
const modal = () => page.getByRole('dialog')
async function launch() {
  application = await _electron.launch({ executablePath: installed || resolve(root, 'node_modules/electron/dist/electron.exe'), args: installed ? [`--user-data-dir=${data}`] : [resolve(root, 'tests/electron-launch.cjs')], cwd: root, env: { ...process.env, JIAZI_TEST_DATA: data } })
  page = await application.firstWindow()
  page.setDefaultTimeout(15_000)
  page.on('pageerror', (error) => errors.push(error.message))
  await page.getByRole('heading', { name: /欢迎使用 Jiazi Vault|解锁保险库/ }).waitFor()
}
async function unlock(secret = password) {
  await page.getByPlaceholder('主密码', { exact: true }).fill(secret)
  await page.getByRole('button', { name: '解锁', exact: true }).click()
  await page.getByRole('heading', { name: '全部条目', exact: true }).waitFor()
}
async function dialogs(response, path) {
  await application.evaluate(({ dialog }, { response, path }) => {
    dialog.showMessageBox = async (_window, options) => {
      if (options.defaultId !== 0 || options.cancelId !== 0) throw new Error('Unsafe confirmation default')
      return { response }
    }
    dialog.showSaveDialog = async () => ({ canceled: !path, filePath: path })
    dialog.showOpenDialog = async () => ({ canceled: !path, filePaths: path ? [path] : [] })
  }, { response, path })
}
async function openItem(title) {
  await page.locator('.item-main').filter({ hasText: title }).first().click()
  await page.getByPlaceholder('变量集名称').waitFor()
}
async function save() {
  await modal().getByRole('button', { name: '保存', exact: true }).click()
  await page.getByPlaceholder('变量集名称').waitFor({ state: 'hidden' })
}
try {
  await launch()
  originalClipboard = await application.evaluate(async ({ clipboard }) => clipboard.readText())
  console.log('RUNTIME ' + JSON.stringify(await application.evaluate(() => process.versions)))
  await createVaultThroughUI(page, password)
  const project = await call('create_project', { project: { name: 'ENV project' } })
  await page.getByRole('link', { name: '设置', exact: true }).click()
  await page.getByRole('link', { name: '全部条目', exact: true }).click()
  await page.getByRole('button', { name: '新建', exact: true }).click()
  await modal().locator('.n-select').first().click()
  await page.locator('.n-base-select-menu').getByText('环境变量集', { exact: true }).click()
  await page.getByPlaceholder('变量集名称').fill('Env Production')
  await modal().locator('.n-select').nth(1).click()
  await page.locator('.n-base-select-menu').getByText('ENV project', { exact: true }).click()
  await modal().locator('.n-select').nth(2).click()
  await page.locator('.n-base-select-menu').getByText('Production', { exact: true }).click()
  await modal().getByRole('button', { name: '导入 .env', exact: true }).click()
  await page.getByRole('textbox', { name: '.env 导入内容' }).fill('TOKEN=one\nTOKEN=two\n1_BAD=bad')
  await modal().getByRole('button', { name: '预览解析结果' }).click()
  await page.getByText(/第 2 行：变量 TOKEN 重复/).waitFor()
  assert.equal(await modal().getByRole('button', { name: /加入编辑/ }).isDisabled(), true)
  assert.equal(await modal().getByRole('button', { name: '保存', exact: true }).isDisabled(), true)
  pass('invalid lines and duplicate names are visible and block import and save')
  await modal().getByRole('button', { name: '编辑导入内容' }).click()
  const source = '# comment\r\nEMPTY=\r\nTOKEN=secret-token\r\nMULTI="first\nsecond"\r\nSPACED=\'  keep # space  \'\r\n'
  await page.getByRole('textbox', { name: '.env 导入内容' }).fill(source)
  await modal().getByRole('button', { name: '预览解析结果' }).click()
  assert.equal(await page.getByRole('textbox', { name: '.env 导入内容' }).count(), 0)
  assert.equal((await modal().innerText()).includes('secret-token'), false)
  await modal().getByRole('button', { name: /将 4 个变量加入编辑/ }).click()
  assert.equal(await modal().locator('textarea').count(), 0)
  await save()
  let summary = (await call('list_items', {})).find((item) => item.title === 'Env Production')
  const expected = parseNodeEnv(source)
  assert.equal(summary.projectId, project.id)
  assert.equal(summary.environment, 'production')
  assert.equal(summary.fields, undefined)
  assert.deepEqual((await call('get_item', { id: summary.id })).fields, expected)
  for (const [placeholder, label] of [['全部类型', '环境变量集'], ['全部项目', 'ENV project'], ['全部环境', 'Testing']]) {
    await page.locator('.filters .n-select').filter({ hasText: placeholder }).click()
    await page.locator('.n-base-select-menu').getByText(label, { exact: true }).click()
  }
  assert.equal(await page.locator('.item-main').count(), 0)
  await page.locator('.filters .n-select').filter({ hasText: 'Testing' }).click()
  await page.locator('.n-base-select-menu').getByText('Production', { exact: true }).click()
  assert.equal(await page.locator('.item-main').count(), 1)
  pass('paste import preview masks values and encrypted save retains empty and multiline values with project/environment')
  await openItem('Env Production')
  await modal().getByRole('button', { name: '显示MULTI', exact: true }).click()
  await page.getByRole('textbox', { name: '字段值MULTI', exact: true }).fill('edited\nline')
  expected.MULTI = 'edited\nline'
  await modal().getByRole('button', { name: '复制MULTI', exact: true }).click()
  await page.getByText('已复制到剪贴板', { exact: true }).first().waitFor()
  assert.equal(await application.evaluate(async ({ clipboard }) => clipboard.readText()), expected.MULTI)
  await modal().getByRole('button', { name: '复制EMPTY', exact: true }).click()
  await page.waitForTimeout(100)
  assert.equal(await application.evaluate(async ({ clipboard }) => clipboard.readText()), '')
  await modal().getByRole('button', { name: '新增变量', exact: true }).click()
  await page.getByRole('textbox', { name: '变量名称', exact: true }).last().fill('TOKEN')
  assert.equal(await modal().getByRole('button', { name: '保存', exact: true }).isDisabled(), true)
  await page.getByRole('textbox', { name: '变量名称', exact: true }).last().fill('NEW')
  await page.getByRole('textbox', { name: '字段值NEW', exact: true }).fill('added')
  await modal().getByRole('button', { name: '删除字段NEW', exact: true }).click()
  await save()
  pass('edit, add/delete, duplicate validation and per-variable copy preserve multiline and empty values')
  await openItem('Env Production')
  await dialogs(0)
  await modal().getByRole('button', { name: '复制完整 .env', exact: true }).click()
  await page.waitForTimeout(100)
  assert.equal(await application.evaluate(async ({ clipboard }) => clipboard.readText()), '')
  await dialogs(1)
  await modal().getByRole('button', { name: '复制完整 .env', exact: true }).click()
  await page.getByText('已复制完整 .env 内容', { exact: true }).waitFor()
  assert.deepEqual(parseNodeEnv(await application.evaluate(async ({ clipboard }) => clipboard.readText())), expected)
  const exported = resolve(data, '.env.production')
  await dialogs(0, exported)
  assert.equal(await call('export_env', { fields: expected, destination: 'file' }), null)
  await assert.rejects(readFile(exported), /ENOENT/)
  await dialogs(1, exported)
  await modal().getByRole('button', { name: '导出 .env 文件', exact: true }).click()
  await page.getByText('已导出 .env.production', { exact: true }).waitFor()
  assert.deepEqual(parseNodeEnv(await readFile(exported, 'utf8')), expected)
  assert.deepEqual(await application.evaluate((_electron, text) => process.getBuiltinModule('node:util').parseEnv(text), await readFile(exported, 'utf8')), expected)
  pass('full copy and file export require confirmation; cancellation writes nothing; Node parses identical values')
  await modal().getByRole('button', { name: '导入 .env', exact: true }).click()
  await modal().getByRole('button', { name: '选择 .env 文件' }).click()
  await page.getByText(/变量 TOKEN 已在当前变量集中/).waitFor()
  assert.equal(await modal().getByRole('button', { name: /加入编辑/ }).isDisabled(), true)
  await modal().getByRole('button', { name: '取消导入' }).click()
  const importPath = resolve(data, '.env.extra')
  await writeFile(importPath, 'FILE_VALUE=from-file\n', 'utf8')
  await dialogs(1, importPath)
  await modal().getByRole('button', { name: '导入 .env', exact: true }).click()
  await modal().getByRole('button', { name: '选择 .env 文件' }).click()
  await modal().getByRole('button', { name: /将 1 个变量加入编辑/ }).click()
  expected.FILE_VALUE = 'from-file'
  await save()
  pass('native file import previews, rejects collisions and appends validated variables')
  await application.close()
  await launch()
  await unlock()
  assert.deepEqual((await call('get_item', { id: summary.id })).fields, expected)
  const backupPath = resolve(data, 'env.jvault')
  await dialogs(1, backupPath)
  await call('delete_item', { id: summary.id })
  assert.equal((await call('list_items', { trashed: true }))[0].id, summary.id)
  await call('create_backup')
  await call('delete_item', { id: summary.id, permanently: true })
  await call('restore_backup', { password })
  await unlock()
  assert.equal((await call('list_items', { trashed: true }))[0].id, summary.id)
  await call('restore_item', { id: summary.id })
  assert.deepEqual((await call('get_item', { id: summary.id })).fields, expected)
  await call('change_master_password', { currentPassword: password, newPassword: password + '-new' })
  await unlock(password + '-new')
  assert.deepEqual((await call('get_item', { id: summary.id })).fields, expected)
  pass('restart, trash, backup restore and master password change retain all env values through real IPC')
  await openItem('Env Production')
  const saveBounds = await modal().getByRole('button', { name: '保存', exact: true }).boundingBox()
  assert.ok(saveBounds && saveBounds.y + saveBounds.height <= await page.evaluate(() => window.innerHeight), 'Save must stay visible in the env editor')
  await page.screenshot({ path: resolve(output, installed ? 'env-installed.png' : 'env-editor.png') })
  await application.evaluate(({ dialog }) => { dialog.showMessageBox = () => new Promise((resolve) => { globalThis.envResolveConfirm = resolve }) })
  await page.evaluate((fields) => { window.envPending = window.jiaziVault.invoke('export_env', { fields, destination: 'file' }).then(() => 'success', () => 'rejected') }, expected)
  while (!await application.evaluate(() => Boolean(globalThis.envResolveConfirm))) await page.waitForTimeout(20)
  await call('lock_vault')
  await page.getByRole('heading', { name: '解锁保险库', exact: true }).waitFor()
  await application.evaluate(() => globalThis.envResolveConfirm({ response: 1 }))
  assert.equal(await page.evaluate(() => window.envPending), 'rejected')
  assert.equal(await page.getByPlaceholder('变量集名称').count(), 0)
  for (const [command, args] of [['get_item', { id: summary.id }], ['read_env_file'], ['export_env', { fields: expected, destination: 'clipboard' }]]) await assert.rejects(call(command, args), /VAULT_LOCKED/)
  await page.waitForTimeout(100)
  assert.equal(await application.evaluate(async ({ clipboard }) => clipboard.readText()), '')
  assert.equal((await readdir(data)).some((name) => name.endsWith('.tmp')), false)
  await unlock(password + '-new')
  await application.evaluate(({ dialog }) => { dialog.showOpenDialog = () => new Promise((resolve) => { globalThis.envResolveOpen = resolve }) })
  await openItem('Env Production')
  await modal().getByRole('button', { name: '导入 .env', exact: true }).click()
  await modal().getByRole('button', { name: '选择 .env 文件' }).click()
  while (!await application.evaluate(() => Boolean(globalThis.envResolveOpen))) await page.waitForTimeout(20)
  await call('lock_vault')
  await application.evaluate((_electron, path) => globalThis.envResolveOpen({ canceled: false, filePaths: [path] }), importPath)
  await page.getByRole('heading', { name: '解锁保险库', exact: true }).waitFor()
  assert.equal(await page.getByRole('textbox', { name: '.env 导入内容' }).count(), 0)
  assert.equal((await page.locator('body').innerText()).includes('from-file'), false)
  pass('lock destroys editor/import preview, clears clipboard, denies sensitive IPC and cancels pending import/export')
  assert.deepEqual(errors, [])
} catch (error) {
  errors.push(String(error))
  await page?.screenshot({ path: resolve(output, 'env-failure.png') }).catch(() => {})
  console.log(await page?.locator('body').innerText().catch(() => ''))
  throw error
} finally {
  if (application) {
    await application.evaluate(async ({ clipboard }, original) => clipboard.writeText(original ?? ''), originalClipboard).catch(() => {})
    await application.close().catch(() => {})
  }
  await writeFile(resolve(output, installed ? 'env-installed-report.json' : 'env-smoke-report.json'), JSON.stringify({ report, errors, data, installed, boundaries: 'Real Electron production UI/IPC/SQLite/crypto/clipboard. Native file choices and confirmation responses injected; no personal vault. OS lock/sleep are covered separately.' }, null, 2))
}
